trigger:
  branches:
    include:
      - main

pool:
  name: 'Self-Hosted Pool'  # Name of the pool for the self-hosted agent

steps:
# Optionally install Git (which includes tr command) on the agent machine
# Uncomment this task if you want to try installing Git
- task: PowerShell@2
  displayName: 'Install Git (includes tr command)'
  inputs:
    targetType: 'inline'
    script: |
      if (!(Get-Command git -ErrorAction SilentlyContinue)) {
        Write-Host "Git not found. Installing..."
        choco install git -y
        refreshenv
      } else {
        Write-Host "Git is already installed."
      }

# Install .NET Core SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Restore dependencies for the DDEyC_API project only
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(Build.SourcesDirectory)/DDEyC_API/DDEyC_API.csproj'

# Build the DDEyC_API project only
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)/DDEyC_API/DDEyC_API.csproj'
    arguments: '--configuration Release'

# Publish the DDEyC_API project to a temporary directory for deployment
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '$(Build.SourcesDirectory)/DDEyC_API/DDEyC_API.csproj'
    publishWebProjects: true
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

# Copy the published files to the remote server using SSH
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'SSH Devops'
    sourceFolder: '$(Build.ArtifactStagingDirectory)'
    targetFolder: 'C:/inetpub/WebAPI'
    cleanTargetFolder: false

# Execute SSH commands on the remote server to restart IIS
- task: SSH@0
  inputs:
    sshEndpoint: 'SSH Devops'
    runOptions: 'inline'
    inline: |
      powershell.exe -Command "iisreset"