trigger:
  branches:
    include:
      - main

pool:
  name: 'Self-Hosted Pool'

variables:
- group: DeploymentCredentials  # Links to the variable group you created

steps:
# Install .NET Core SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Restore dependencies for the DDEyC_API project only
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(Build.SourcesDirectory)/DDEyC_API/DDEyC_API.csproj'

# Build the DDEyC_API project only
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)/DDEyC_API/DDEyC_API.csproj'
    arguments: '--configuration Release'

# Publish the DDEyC_API project to a temporary directory for deployment
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '$(Build.SourcesDirectory)/DDEyC_API/DDEyC_API.csproj'
    publishWebProjects: true
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

# Copy the published files to the remote server using PowerShell
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $ErrorActionPreference = "Stop"
      $VerbosePreference = "Continue"
      $source = "$(Build.ArtifactStagingDirectory)"
      $destination = "\\158.222.102.253\C$\inetpub\WebAPI"
      $username = "$(Username)"
      $password = "$(Password)"
      
      try {
        Write-Verbose "Attempting to connect to remote share..."
        $netUseResult = net use $destination /user:$username $password 2>&1
        if ($LASTEXITCODE -ne 0) {
          throw "Failed to connect to remote share. Net Use output: $netUseResult"
        }
        Write-Verbose "Connected to remote share successfully."
        
        Write-Verbose "Copying files..."
        $robocopyResult = robocopy $source $destination /E /NFL /NDL /NJH /NJS /nc /ns /np
        if ($LASTEXITCODE -gt 7) {
          throw "Robocopy encountered errors. Exit code: $LASTEXITCODE"
        }
        Write-Verbose "Files copied successfully."
      }
      catch {
        Write-Error "An error occurred: $_"
        throw
      }
      finally {
        if (Test-Path $destination) {
          Write-Verbose "Removing network connection..."
          net use $destination /delete
        }
      }
# Restart IIS on the remote server using PowerShell
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $ErrorActionPreference = "Stop"
      $username = "$(Username)"
      $password = ConvertTo-SecureString "$(Password)" -AsPlainText -Force
      $credential = New-Object System.Management.Automation.PSCredential($username, $password)
      
      try {
        Write-Host "Attempting to restart IIS..."
        Invoke-Command -ComputerName "158.222.102.253" -ScriptBlock {
          Import-Module WebAdministration
          $result = iisreset
          if ($LASTEXITCODE -ne 0) {
            throw "IISReset failed with exit code $LASTEXITCODE. Output: $result"
          }
          Write-Host $result
        } -Credential $credential -ErrorAction Stop
        
        Write-Host "IIS restarted successfully."
      }
      catch {
        Write-Error "An error occurred while restarting IIS: $_"
        throw
      }