trigger:
  branches:
    include:
      - main

pool:
  name: 'Self-Hosted Pool'  # Name of the pool for the self-hosted agent

steps:
# Install .NET Core SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Restore dependencies for the DDEyC_API project only
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(Build.SourcesDirectory)/DDEyC_API/DDEyC_API.csproj'

# Build the DDEyC_API project only
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)/DDEyC_API/DDEyC_API.csproj'
    arguments: '--configuration Release'

# Publish the DDEyC_API project to a temporary directory for deployment
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '$(Build.SourcesDirectory)/DDEyC_API/DDEyC_API.csproj'
    publishWebProjects: true
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

# Copy the published files to the remote server using SSH
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'SSH Devops'
    sourceFolder: '$(Build.ArtifactStagingDirectory)'
    targetFolder: 'C:/inetpub/WebAPI'
    cleanTargetFolder: false

# Execute SSH commands on the remote server to restart IIS (Option 1: Inline command)
- task: SSH@0
  inputs:
    sshEndpoint: 'SSH Devops'
    runOptions: 'inline'
    inline: |
      powershell.exe -Command "iisreset"

# Alternative: Execute SSH commands on the remote server to restart IIS (Option 2: Using a script)
# Uncomment this task and comment out the previous SSH task if you want to try this approach
# - task: SSH@0
#   inputs:
#     sshEndpoint: 'SSH Devops'
#     runOptions: 'script'
#     scriptPath: '$(Build.SourcesDirectory)/restart-iis.ps1'

# Install Git for Windows (which includes tr command)
# Uncomment this task if you want to try installing Git for Windows
# - task: PowerShell@2
#   inputs:
#     targetType: 'inline'
#     script: |
#       choco install git -y
#       refreshenv